// Code generated by MockGen. DO NOT EDIT.
// Source: xbooklab/models (interfaces: UserBehaviorRepository)

// Package models is a generated GoMock package.
package models

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUserBehaviorRepository is a mock of UserBehaviorRepository interface.
type MockUserBehaviorRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserBehaviorRepositoryMockRecorder
}

// MockUserBehaviorRepositoryMockRecorder is the mock recorder for MockUserBehaviorRepository.
type MockUserBehaviorRepositoryMockRecorder struct {
	mock *MockUserBehaviorRepository
}

// NewMockUserBehaviorRepository creates a new mock instance.
func NewMockUserBehaviorRepository(ctrl *gomock.Controller) *MockUserBehaviorRepository {
	mock := &MockUserBehaviorRepository{ctrl: ctrl}
	mock.recorder = &MockUserBehaviorRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserBehaviorRepository) EXPECT() *MockUserBehaviorRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserBehaviorRepository) Create(arg0 UserInteraction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserBehaviorRepositoryMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserBehaviorRepository)(nil).Create), arg0)
}

// GetAll mocks base method.
func (m *MockUserBehaviorRepository) GetAll() ([]UserInteraction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]UserInteraction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockUserBehaviorRepositoryMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockUserBehaviorRepository)(nil).GetAll))
}
